### ISSUE TITLE
List View for MyCompanies & All Companies + Multi Select

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/PM-Gen-2-Designs#3]

**Comment by juliettemekikianpm** [comment]
Not total build-out  
Desktop and mobile

**Comment by jaahmuhl** [comment]
All Companies
<img width="1006" alt="Screen Shot 2020-07-07 at 11 58 10 AM" src="https://user-images.githubusercontent.com/3681694/86809320-c0528300-c049-11ea-8745-5a50c53d7075.png">

My Companies
<img width="1000" alt="Screen Shot 2020-07-07 at 11 58 34 AM" src="https://user-images.githubusercontent.com/3681694/86809201-9bf6a680-c049-11ea-9c8c-383c65a43af1.png">

Multi Select
<img width="998" alt="Screen Shot 2020-07-07 at 11 58 19 AM" src="https://user-images.githubusercontent.com/3681694/86809251-ae70e000-c049-11ea-9eb8-5bee263570e5.png">
